name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ secrets.AWS_REGION }}
    - name: Build and push microservice1
      run: |
        docker build -t ${{ secrets.ECR_REGISTRY }}/microservice1:${{ github.sha }} ./microservice1
        docker push ${{ secrets.ECR_REGISTRY }}/microservice1:${{ github.sha }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name my-eks-cluster
    - name: Deploy to EKS
      run: |
        kubectl set image deployment/microservice1 microservice1=${{ secrets.ECR_REGISTRY }}/microservice1:${{ github.sha }}